<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<ApplicationIcon>Ressources\c2flux.ico</ApplicationIcon>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<NoWarn>$(NoWarn);CA1416</NoWarn>

		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>false</SelfContained>
		
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<AssemblyName>c2flux</AssemblyName>
		<RootNamespace>c2flux</RootNamespace>
		<StartupObject>c2flux.Program</StartupObject>

		<Authors>Daniel Capilla</Authors>
		<Company>Daniel Capilla</Company>
		<Product>c² flux - Tree Scanner</Product>
		<Copyright>Copyright © Daniel Capilla</Copyright>

		<Version>1.0.2</Version>
		<AssemblyVersion>1.0.2</AssemblyVersion>
		<FileVersion>1.0.2</FileVersion>
		<InformationalVersion>1.0.2</InformationalVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	

	<ItemGroup>
		<PackageReference Include="itsWindows11.NtfsReader" Version="0.1.0" />
		<PackageReference Include="AntdUI" Version="2.4.3" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.22" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Ressources\c2flux.ico">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
		<Content Include="Ressources\c2flux.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
		<EmbeddedResource Include="Ressources\c2flux.ico" />
		<EmbeddedResource Include="Ressources\c2flux.png" />
		<EmbeddedResource Include="Ressources\ko-fi.png" />
		<EmbeddedResource Include="Ressources\molotov.jpg" />
	</ItemGroup>


	<ItemGroup>
		<None Update="Ressources\Languages\lang_*.json">
			<TargetPath>Languages\%(Filename)%(Extension)</TargetPath>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</None>

		<None Update="Ressources\Languages\lang_de.json;Ressources\Languages\lang_en.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>

		<None Update="Ressources\Licenses\*.*">
			<TargetPath>Licenses\%(Filename)%(Extension)</TargetPath>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</None>
	</ItemGroup>

</Project>